services:
  app-core:
    build:
      context: .
      dockerfile: core-module/Dockerfile
    ports:
      - "8080"

  web-app:
    build:
      context: .
      dockerfile: web-app/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - app-core

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "443:80"
    depends_on:
      - app-core
      - web-app