/*
 AI generated schema.
 You could watch README.md workflow or simply:
 I created the Entity relation model
 And it would take me much time writing schema

 what is lower case - written by hand
 */

DROP TABLE IF EXISTS "reservations";
DROP TABLE IF EXISTS "tables";
DROP TABLE IF EXISTS "user_restaurant_permissions";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "zones";
drop table if exists "restaurants";

create table if not exists "restaurants" (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    address varchar(500) not null,
    phone varchar(20),
    email varchar(100),

    open_time time default '9:00:00',
    close_time time default '20:00:00',

    created_at timestamptz default current_timestamp,
    updated_at timestamptz default current_timestamp,
    is_deleted boolean default false
);

CREATE TABLE IF NOT EXISTS "zones" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "users" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    role VARCHAR(50) DEFAULT 'USER',
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE "user_restaurant_permissions" (
    user_id BIGINT REFERENCES "users"(id),
    restaurant_id BIGINT REFERENCES "restaurants"(id),
    role VARCHAR(50),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, restaurant_id)
);

CREATE TABLE IF NOT EXISTS "tables" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT NOT NULL,
    restaurant_id bigint not null,
    capacity INT NOT NULL,
    pos_x FLOAT NOT NULL,
    pos_y FLOAT NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_tables_zones FOREIGN KEY (zone_id) REFERENCES "zones"(id)
);

CREATE TABLE IF NOT EXISTS "reservations" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_res_users FOREIGN KEY (user_id) REFERENCES "users"(id),
    CONSTRAINT fk_res_tables FOREIGN KEY (table_id) REFERENCES "tables"(id)
);

insert into "restaurants" (name, address, phone, email)
values ( 'main_restaurant', 'Tartu', '+372 53293281', 'main_restaurant@gmail.com');

INSERT INTO "zones" (name)
VALUES ('Silent place');

INSERT INTO "zones" (name)
VALUES ('Near the window');

INSERT INTO "zones" (name)
VALUES ('Kindergarten');

INSERT INTO "zones" (name)
VALUES ('Center');

INSERT INTO "tables" (zone_id, restaurant_id,capacity, pos_x, pos_y)
VALUES (1,1, 2, 100, 100.0);

INSERT INTO "tables" (zone_id, restaurant_id, capacity, pos_x, pos_y)
VALUES (2, 1, 2, 100, 200.0);

INSERT INTO "tables" (zone_id, restaurant_id, capacity, pos_x, pos_y)
VALUES (2, 1, 2, 100, 300.0);

INSERT INTO "tables" (zone_id, restaurant_id, capacity, pos_x, pos_y)
VALUES (1, 1, 2, 100, 400.0);

INSERT INTO "tables" (zone_id, restaurant_id, capacity, pos_x, pos_y)
VALUES (3, 1, 4, 700.0, 200.0);

INSERT INTO "tables" (zone_id, restaurant_id, capacity, pos_x, pos_y)
VALUES (3, 1, 4, 700.0, 300.0);

INSERT INTO "tables" (zone_id, restaurant_id, capacity, pos_x, pos_y)
VALUES (3, 1, 4, 700.0, 400.0);

INSERT INTO "tables" (zone_id, restaurant_id, capacity, pos_x, pos_y)
VALUES (4, 1, 8, 400, 400);

INSERT INTO "tables" (zone_id, restaurant_id, capacity, pos_x, pos_y)
VALUES (4, 1, 8, 400, 200);