spring.application.name=persistence-module

spring.datasource.url=jdbc:h2:file:./data/my_restaurant_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always