spring.application.name=persistence-module

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://192.168.10.249:5432/my_restaurant_db}
spring.datasource.username=${DATABASE_USER:restaurant_admin}
spring.datasource.password=${DATABASE_PASSWORD:1234a}
spring.datasource.driverClassName=org.postgresql.Driver