spring.application.name=persistence-module

spring.datasource.url=jdbc:postgresql://192.168.10.249:5432/my_restaurant_db
spring.datasource.username=restaurant_admin
spring.datasource.password=1234a
spring.datasource.driverClassName=org.postgresql.Driver