/*
 AI generated schema.
 You could watch README.md workflow or simply:
 I created the Entity relation model
 And it would take me much time writing schema
 */

-- Удаляем в обратном порядке из-за связей (опционально, если хочешь пересоздать файл)
DROP TABLE IF EXISTS "reservations";
DROP TABLE IF EXISTS "tables";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "zones";

CREATE TABLE IF NOT EXISTS "zones" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "users" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    second_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    role VARCHAR(50) DEFAULT 'USER',
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "tables" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT NOT NULL,
    capacity INT NOT NULL,
    pos_x FLOAT NOT NULL,
    pos_y FLOAT NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_tables_zones FOREIGN KEY (zone_id) REFERENCES "zones"(id)
);

CREATE TABLE IF NOT EXISTS "reservations" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    reservation_start TIMESTAMP NOT NULL,
    reservation_end TIMESTAMP NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_res_users FOREIGN KEY (user_id) REFERENCES "users"(id),
    CONSTRAINT fk_res_tables FOREIGN KEY (table_id) REFERENCES "tables"(id)
);

INSERT INTO "zones" (name)
VALUES ('Vaikne nurk');

INSERT INTO "zones" (name)
VALUES ('Akna all');

INSERT INTO "zones" (name)
VALUES ('Laste mangunurk');

INSERT INTO "tables" (zone_id, capacity, pos_x, pos_y)
VALUES (1, 2, 10.5, 20.0);

INSERT INTO "tables" (zone_id, capacity, pos_x, pos_y)
VALUES (2, 2, 30.5, 90.0);

INSERT INTO "tables" (zone_id, capacity, pos_x, pos_y)
VALUES (3, 4, 25.5, 0.0);

INSERT INTO "tables" (zone_id, capacity, pos_x, pos_y)
VALUES (3, 6, 25.5, 0.0);

INSERT INTO "tables" (zone_id, capacity, pos_x, pos_y)
VALUES (2, 8, 45.5, 13.0);

INSERT INTO "tables" (zone_id, capacity, pos_x, pos_y)
VALUES (2, 6, 15.5, 0.0);

INSERT INTO "tables" (zone_id, capacity, pos_x, pos_y)
VALUES (1, 4, 0.5, 30.0);

INSERT INTO "users" (first_name, second_name, email, password_hash)
VALUES ('Fedos', 'secondName', 'example@gmail.com', 'sha');

INSERT INTO "reservations" (user_id, table_id, reservation_start, reservation_end)
VALUES (1, 1, '2026-03-01 18:00:00', '2026-03-01 20:00:00');