/*
 AI generated schema.
 You could watch README.md workflow or simply:
 I created the Entity relation model
 And it would take me much time writing schema
 */

CREATE TABLE IF NOT EXISTS "zone" (
    zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    capacity INT
    );

CREATE TABLE IF NOT EXISTS "user" (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    second_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'USER'
);

CREATE TABLE IF NOT EXISTS "table" (
    table_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT NOT NULL,
    capacity INT NOT NULL,
    pos_x FLOAT NOT NULL,
    pos_y FLOAT NOT NULL,
    CONSTRAINT fk_table_zone FOREIGN KEY (zone_id) REFERENCES "zone"(zone_id)
);

CREATE TABLE IF NOT EXISTS reservation (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reservation_time TIMESTAMP NOT NULL,
    reservation_end TIMESTAMP NOT NULL,
    CONSTRAINT fk_res_table FOREIGN KEY (table_id) REFERENCES "table"(table_id),
    CONSTRAINT fk_res_user FOREIGN KEY (user_id) REFERENCES "user"(user_id)
);