spring.application.name=web-app
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.grpc.client.default-channel.address=${GRPC_CLIENT_DEFAULT_CHANNEL_ADDRESS:static://localhost:9090}
spring.grpc.client.default-channel.negotiation-type=${GRPC_CLIENT_DEFAULT_CHANNEL_NEGOTIATION_TYPE:plaintext}